# Generated by Django 3.0.5 on 2020-07-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_contact',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='post_owner',
            field=models.CharField(default='', max_length=100),
        ),
    ]
